// generated by stringer -type=BinOpType; DO NOT EDIT

package ssa

import "fmt"

const _BinOpType_name = "BinOpAddBinOpSubBinOpMulBinOpSDivBinOpUDivBinOpSRemBinOpURemBinOpFAddBinOpFSubBinOpFMulBinOpFDivBinOpFRemBinOpShlBinOpLShrBinOpRShrBinOpAndBinOpOrBinOpXor"

var _BinOpType_index = [...]uint8{8, 16, 24, 33, 42, 51, 60, 69, 78, 87, 96, 105, 113, 122, 131, 139, 146, 154}

func (i BinOpType) String() string {
	if i < 0 || i >= BinOpType(len(_BinOpType_index)) {
		return fmt.Sprintf("BinOpType(%d)", i)
	}
	hi := _BinOpType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _BinOpType_index[i-1]
	}
	return _BinOpType_name[lo:hi]
}
