// generated by stringer -type=ConvertType; DO NOT EDIT

package ssa

import "fmt"

const _ConvertType_name = "ConvertSExtConvertZExtConvertTruncConvertBitcastConvertFExtConvertFTruncConvertFToUIConvertFToSIConvertUIToFConvertSIToFConvertPtrToIntConvertIntToPtr"

var _ConvertType_index = [...]uint8{11, 22, 34, 48, 59, 72, 84, 96, 108, 120, 135, 150}

func (i ConvertType) String() string {
	if i < 0 || i >= ConvertType(len(_ConvertType_index)) {
		return fmt.Sprintf("ConvertType(%d)", i)
	}
	hi := _ConvertType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _ConvertType_index[i-1]
	}
	return _ConvertType_name[lo:hi]
}
