// generated by stringer -type=IntPredicate; DO NOT EDIT

package ssa

import "fmt"

const _IntPredicate_name = "IntEQIntNEQIntUGTIntUGEIntULTIntULEIntSGTIntSGEIntSLTIntSLE"

var _IntPredicate_index = [...]uint8{5, 11, 17, 23, 29, 35, 41, 47, 53, 59}

func (i IntPredicate) String() string {
	if i < 0 || i >= IntPredicate(len(_IntPredicate_index)) {
		return fmt.Sprintf("IntPredicate(%d)", i)
	}
	hi := _IntPredicate_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _IntPredicate_index[i-1]
	}
	return _IntPredicate_name[lo:hi]
}
